#CTH Dynamic Application Configuration
#Sun Oct 04 02:18:28 UTC 2026
app.auth.ldap.base-dn=dc\=cth,dc\=com
app.auth.ldap.url=ldap\://localhost\:389
app.auth.ldap.user-dn-pattern=uid\={0},ou\=users
app.auth.mode=LOCAL
app.name=CTH Enterprise Dynamic System
app.security.max-failed-attempts=5
app.security.mfa.enabled=false
app.security.password.expiration-days=90
db.driver=org.h2.Driver
db.password=
db.type=H2
db.url=jdbc\:h2\:mem\:cthdb;DB_CLOSE_DELAY\=-1;DB_CLOSE_ON_EXIT\=FALSE
db.username=sa
