-- Oracle Database DDL and Initial Seed Script for CTH Enterprise Application

CREATE TABLE cth_users (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    full_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    phone VARCHAR2(50),
    role VARCHAR2(50) DEFAULT 'ROLE_USER',
    account_non_locked NUMBER(1) DEFAULT 1 NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    failed_attempt NUMBER(10) DEFAULT 0 NOT NULL,
    password_last_changed TIMESTAMP,
    account_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cth_report_configs (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_name VARCHAR2(255) NOT NULL UNIQUE,
    description VARCHAR2(500),
    query_sql VARCHAR2(2000) NOT NULL,
    target_table VARCHAR2(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Seed Default Admin User (Password: admin123 hashed via BCrypt)
INSERT INTO cth_users (username, password, full_name, email, phone, role, account_non_locked, enabled, failed_attempt, password_last_changed)
VALUES ('admin', '$2a$10$e0MYzXyjpJS7Pd0RVvHwHe11.75X67/7.794m/90yM6v0y4/54432', 'System Administrator', 'admin@cth.com', '+1234567890', 'ROLE_ADMIN', 1, 1, 0, CURRENT_TIMESTAMP);

-- Seed Default Online Report
INSERT INTO cth_report_configs (report_name, description, query_sql, target_table)
VALUES ('User Activity & Status Report', 'List of all registered users and account status', 'SELECT username, full_name, email, role, account_non_locked, enabled, failed_attempt FROM cth_users', 'cth_users');

COMMIT;
